#!/usr/bin/env sh

set +e

db_min_size=5000 # size in kb 5kb

# check backup exists
dbfile=$(aws s3api head-object --bucket ${S3_BUCKET_BACKUPS_DB} --key ${BACKUP_FILE} --output json || echo '{"ContentLength": 0}')

if [ $(printf "%s" "$dbfile" | jq '.ContentLength') == 0 ]; then
  echo "File not found, try again"
  exit 1
else
  if [ $(printf "%s" "$dbfile" | jq '.ContentLength') -lt "$db_min_size" ]; then
    echo "ERROR: Backup size is $(printf "%s" "$dbfile" | jq '.ContentLength'), which is less then minimal $db_min_size, please try using another file"
    exit 1
  else
    echo "DB backup is Ok to restore"
  fi
fi

exec "$@"