#!/usr/bin/env sh

set +e

# download backup archive from s3 bucket
aws s3 cp s3://${S3_BUCKET_BACKUPS_DB}/${BACKUP_FILE} .
gunzip -c ${BACKUP_FILE} > latest.dump

# close active sessions
psql ${POSTGRESQL_URI} -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '${DB_NAME}' AND pid <> pg_backend_pid();"

# recreate empty db
psql ${POSTGRESQL_URI} -c "drop database ${DB_NAME}"
psql ${POSTGRESQL_URI} -c "create database ${DB_NAME}"

# push dump
psql ${POSTGRESQL_URI} --dbname "${DB_NAME}" -f latest.dump

exec "$@"