name: Build and push pgdump docker image

on:
  push:
    branches:
      - main

jobs:
  build-11:
    name: v11
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: v11
        uses: docker/build-push-action@v2
        with:
          context: .
          args: --build-arg PG_VERSION=11
          push: true
          tags: |
            gatewayfm/pg-dump-s3:11

      - name: Send notification to Slack
        uses: skolobov/gh-action-slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEPLOYS }}
        if: failure()

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0
  build-12:
    name: v12
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: v12
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: PG_VERSION=12
          tags: |
            gatewayfm/pg-dump-s3:12

      - name: Send notification to Slack
        uses: skolobov/gh-action-slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEPLOYS }}
        if: failure()

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0
