name: Build and push pgdump docker image

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build and push Docker image
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gatewayfm/pg-dump-s3:${{ github.sha }}
            gatewayfm/pg-dump-s3:latest

      - name: Send notification to Slack
        uses: skolobov/gh-action-slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEPLOYS }}
        if: always()

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0